### ISSUE TITLE
Nextflow version

### ISSUE THREAD

**Issue by JamesZlosnik** [phac-nml/legiovue#1]
In my initial tests the pipeline failed.  As our global install of Nextflow is ~ version 21, I tried a new version (22.10.1 which I was using for something else) that then elicited the error that a minimum version of 23.10.1 is required. I tried then version 24.10.3 (the most current release) and that also failed.  So tried with the minimum pinned version of 23.10.1.  

Suggest to update readme with Nextflow version requirements. Perhaps also additionally make a note if Nextflow Version 24 does not work?

**Comment by DarianHole** [comment]
Thanks @JamesZlosnik for the report! I can add that in for sure!! For failing on the 24.10.3 version it might have to do with a script permission issue I was alerted to and fixing in #2

**Comment by JamesZlosnik** [comment]
Thanks @DarianHole!!  

24.10.3 might be a local issue, I'll try again with #2 as I also encountered a permissions issue on the CREATE_ABUNDANCE_FILTER step and was just about to submit an issue for that one too :)
